spring:
  data:
    redis:
      password: Wasd2333
      host: localhost
      timeout: 3000
  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Wasd2333
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
stock:
#  url: https://api.mairui.club/hszbl/fsjy/{id}/dn/036C1631-968C-4CB3-A7BF-EDD824205E03
  platform: xueqiu
  token: xq_a_token=b3431406326557ec3dd801f4465fa86675442339;u=1829624214